# Generated by Django 4.1.1 on 2022-11-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avg_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('private', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
