# Generated by Django 4.1.1 on 2022-11-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_from', models.CharField(blank=True, default='', max_length=100)),
                ('city_to', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=9)),
                ('reserved_seats', models.IntegerField(default=1)),
                ('ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.ride')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger', to='users.user')),
            ],
        ),
    ]
