# Generated by Django 4.1.1 on 2022-11-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], default='driver', max_length=15)),
                ('notification_type', models.CharField(choices=[('accept_req', 'Accept Req'), ('reject_req', 'Reject Req'), ('join_req', 'Join Req'), ('edit_info', 'Edit Info'), ('resign_info', 'Resign Info'), ('cancel_info', 'Cancel Info')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.ride')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='users.user')),
            ],
        ),
    ]
